image: python:2.7
build:
  script:
    - pip install -r requirements/dev.txt
    - npm install -g eslint stylelint
test:
  script:
    - flake8 .
    - pytest
    - eslint 'network/static/js/*.js'
    - stylelint 'network/static/css/*.css'
